### PR TITLE
Added Intuita 1-Click Run

### PR DESCRIPTION
**Pull request by mohab-sameh**
Added support for running [Ratchet](https://github.com/mskelton/ratchet/) using the [Intuita VS Code extension](https://marketplace.visualstudio.com/items?itemName=Intuita.intuita-vscode-extension). Now you can 1-click run Ratchet using Intuita VSCE on your projects.

This addition allows you to use Intuita's features with Ratchet, such as:

- Integration with [Intuita's platform](https://www.intuita.io/).
- Dry-run Ratchet (and other codemods).
- Review and edit changes made by the codemod.
- Report issues with codemod accuracy, and get help from a [community of codemod experts](https://www.intuita.io/community).
- Target paths/files during codemod runs.

>💡 To learn more about the features you can use while running Ratchet with Intuita's VSCE, [read the docs here.](https://docs.intuita.io/docs/vs-code-extension/running-codemods)

### CODE REVIEW

**Comment by mskelton** [comment]
@mohab-sameh This looks great.  My only concern is around the language of it. I'm a little concerned that it ties a direct connection between Ratchet and Intuita which could seem to indicate that I'm employed by y'all or something similar. Not that it's necessarily bad or would harm either me or you guys, but it could be a little confusing for users.

Totally fine with it being the first thing before the CLI command, I love what you all are doing and thing it's a great workflow for codemods.

**Comment by mohab-sameh** [comment]
> @mohab-sameh This looks great. My only concern is around the language of it. I'm a little concerned that it ties a direct connection between Ratchet and Intuita which could seem to indicate that I'm employed by y'all or something similar. Not that it's necessarily bad or would harm either me or you guys, but it could be a little confusing for users.
> 
> Totally fine with it being the first thing before the CLI command, I love what you all are doing and thing it's a great workflow for codemods.

Totally understandable. It would be great if we could let users know that the codemod is running on a different platform (Intuita) so that they are aware they will be redirected elsewhere. But definitely, we can tone down the branding if you like or put a non-affiliation note. I can change this or feel free to edit it to something you consider acceptable before merging. Thanks a lot for bringing it up @mskelton

**Comment by mskelton** [comment]
@mohab-sameh Sorry for the delay, busy week for me, but I made a few adjustments to the text and merged this in!

**Comment by mohab-sameh** [comment]
@mskelton no worries. awesome!

**Pull request merged**
